using System.Windows.Controls;
using System.Windows;

namespace ProjectManager.Controls
{
    public partial class ProjectsHeaderToolbar : UserControl
    {
        public ProjectsHeaderToolbar()
        {
            // InitializeComponent will be generated by XAML compilation
            InitializeComponent();
        }
    }
}
